module.exports = {
history:[
  {q:'Year World War II ended?',opts:['1943','1944','1945','1946'],a:2,d:1},
  {q:'First US president?',opts:['Abraham Lincoln','Thomas Jefferson','George Washington','John Adams'],a:2,d:1},
  {q:'Ancient wonder in Alexandria?',opts:['The Colossus','The Lighthouse','The Mausoleum','The Hanging Gardens'],a:1,d:1},
  {q:'Berlin Wall fell in which year?',opts:['1987','1988','1989','1990'],a:2,d:1},
  {q:'Who was the first man on the Moon?',opts:['Buzz Aldrin','Yuri Gagarin','Neil Armstrong','John Glenn'],a:2,d:1},
  {q:'Which empire built the Colosseum?',opts:['Greek','Ottoman','Roman','Byzantine'],a:2,d:1},
  {q:'Year the French Revolution began?',opts:['1776','1789','1799','1804'],a:1,d:1},
  {q:'What ship sank in April 1912?',opts:['Lusitania','Britannic','Titanic','Olympic'],a:2,d:1},
  {q:'Who painted the Sistine Chapel ceiling?',opts:['Leonardo da Vinci','Raphael','Caravaggio','Michelangelo'],a:3,d:1},
  {q:'Which country first gave women the vote?',opts:['USA','UK','New Zealand','France'],a:2,d:1},
  {q:'Who was known as the Iron Lady?',opts:['Angela Merkel','Indira Gandhi','Margaret Thatcher','Golda Meir'],a:2,d:2},
  {q:'The Magna Carta was signed in which year?',opts:['1066','1215','1314','1492'],a:1,d:2},
  {q:'Which civilization built Machu Picchu?',opts:['Maya','Aztec','Inca','Olmec'],a:2,d:2},
  {q:'Who discovered penicillin?',opts:['Louis Pasteur','Alexander Fleming','Joseph Lister','Robert Koch'],a:1,d:2},
  {q:'The Cold War was primarily between?',opts:['USA & China','USA & USSR','UK & Germany','France & Russia'],a:1,d:2},
  {q:'Which war was fought from 1950–1953?',opts:['Vietnam War','Korean War','Gulf War','Falklands War'],a:1,d:2},
  {q:'Who was the last pharaoh of Egypt?',opts:['Nefertiti','Hatshepsut','Cleopatra','Ramesses II'],a:2,d:2},
  {q:'The Renaissance began in which country?',opts:['France','England','Spain','Italy'],a:3,d:2},
  {q:'Who wrote the Communist Manifesto?',opts:['Lenin','Stalin','Karl Marx','Engels alone'],a:2,d:2},
  {q:'What year did the Roman Empire fall?',opts:['376 AD','410 AD','453 AD','476 AD'],a:3,d:3},
  {q:'The Silk Road connected China to where?',opts:['Japan','India','Mediterranean','Australia'],a:2,d:3},
  {q:'Who led India to independence?',opts:['Nehru','Gandhi','Bose','Patel'],a:1,d:3},
  {q:'The Black Death peaked in Europe in?',opts:['1247','1347','1447','1547'],a:1,d:3},
  {q:'Who was the first emperor of China?',opts:['Kublai Khan','Sun Tzu','Qin Shi Huang','Confucius'],a:2,d:3},
  {q:'D-Day landings occurred in which region?',opts:['Belgium','Netherlands','Normandy','Brittany'],a:2,d:3},
  {q:'The Ottoman Empire fell after which war?',opts:['Crimean War','World War I','World War II','Balkan Wars'],a:1,d:3},
  {q:'Who assassinated Abraham Lincoln?',opts:['Lee Harvey Oswald','John Wilkes Booth','Charles Guiteau','Leon Czolgosz'],a:1,d:3},
  {q:'The Industrial Revolution started in?',opts:['France','Germany','Britain','USA'],a:2,d:3}
],
geography:[
  {q:'Capital of Australia?',opts:['Sydney','Melbourne','Brisbane','Canberra'],a:3,d:1},
  {q:'Longest river in the world?',opts:['Amazon','Yangtze','Nile','Mississippi'],a:2,d:1},
  {q:'How many countries in Africa?',opts:['44','54','64','74'],a:1,d:1},
  {q:'Smallest country in the world?',opts:['Monaco','San Marino','Vatican City','Liechtenstein'],a:2,d:1},
  {q:'Which country has the most natural lakes?',opts:['Russia','USA','Brazil','Canada'],a:3,d:1},
  {q:'Capital of Canada?',opts:['Toronto','Vancouver','Ottawa','Montreal'],a:2,d:1},
  {q:'Largest ocean on Earth?',opts:['Atlantic','Indian','Arctic','Pacific'],a:3,d:1},
  {q:'Amazon river flows mostly through which country?',opts:['Colombia','Peru','Venezuela','Brazil'],a:3,d:1},
  {q:'Capital of New Zealand?',opts:['Auckland','Christchurch','Wellington','Dunedin'],a:2,d:1},
  {q:'How many time zones does Russia span?',opts:['9','11','13','15'],a:1,d:1},
  {q:'Tallest mountain on Earth?',opts:['K2','Kangchenjunga','Mount Everest','Lhotse'],a:2,d:2},
  {q:'Which desert is the largest?',opts:['Sahara','Gobi','Arabian','Antarctic'],a:3,d:2},
  {q:'Capital of Turkey?',opts:['Istanbul','Ankara','Izmir','Antalya'],a:1,d:2},
  {q:'Which country has the most islands?',opts:['Indonesia','Philippines','Sweden','Japan'],a:2,d:2},
  {q:'The Dead Sea borders Israel and?',opts:['Egypt','Lebanon','Jordan','Syria'],a:2,d:2},
  {q:'Which continent has the most countries?',opts:['Asia','Europe','Africa','South America'],a:2,d:2},
  {q:'What is the smallest US state?',opts:['Delaware','Connecticut','Rhode Island','Hawaii'],a:2,d:2},
  {q:'Lake Baikal is in which country?',opts:['Mongolia','China','Kazakhstan','Russia'],a:3,d:2},
  {q:'Capital of Switzerland?',opts:['Zurich','Geneva','Bern','Basel'],a:2,d:2},
  {q:'Which strait separates Europe from Asia?',opts:['Gibraltar','Hormuz','Bosphorus','Malacca'],a:2,d:3},
  {q:'Greenland belongs to which country?',opts:['Canada','Iceland','Norway','Denmark'],a:3,d:3},
  {q:'Which African country has the largest population?',opts:['Ethiopia','Egypt','South Africa','Nigeria'],a:3,d:3},
  {q:'The Great Barrier Reef is off which coast?',opts:['Brazil','Australia','Thailand','Mexico'],a:1,d:3},
  {q:'Capital of South Korea?',opts:['Busan','Incheon','Seoul','Daegu'],a:2,d:3},
  {q:'Which river runs through Paris?',opts:['Rhine','Danube','Thames','Seine'],a:3,d:3},
  {q:'Mount Kilimanjaro is in which country?',opts:['Kenya','Uganda','Tanzania','Ethiopia'],a:2,d:3},
  {q:'How many continents are there?',opts:['5','6','7','8'],a:2,d:3},
  {q:'Which is the only continent with no deserts?',opts:['Antarctica','Europe','South America','Australia'],a:1,d:3}
],
movies:[
  {q:'Director of The Dark Knight?',opts:['Spielberg','Ridley Scott','Christopher Nolan','James Cameron'],a:2,d:1},
  {q:'First film to win Best Picture Oscar?',opts:['Sunrise','Wings','The Broadway Melody','Gone with the Wind'],a:1,d:1},
  {q:'Planet in Avatar 2009?',opts:['Pandora','Arrakis','Endor','Hoth'],a:0,d:1},
  {q:'Who plays Iron Man in the MCU?',opts:['Chris Evans','Chris Hemsworth','Robert Downey Jr.','Mark Ruffalo'],a:2,d:1},
  {q:'"You had me at hello" is from which film?',opts:['Sleepless in Seattle','Notting Hill','Jerry Maguire','Pretty Woman'],a:2,d:1},
  {q:'Highest-grossing film of all time?',opts:['Titanic','Avengers: Endgame','Avatar','The Force Awakens'],a:2,d:1},
  {q:'Who directed Pulp Fiction?',opts:['Martin Scorsese','Quentin Tarantino','David Fincher','Coen Brothers'],a:1,d:1},
  {q:'Which actor played Forrest Gump?',opts:['Tom Cruise','Kevin Costner','Tom Hanks','Robin Williams'],a:2,d:1},
  {q:'Year the original Jurassic Park was released?',opts:['1991','1992','1993','1994'],a:2,d:1},
  {q:'Who played The Joker in The Dark Knight?',opts:['Joaquin Phoenix','Jared Leto','Heath Ledger','Jack Nicholson'],a:2,d:2},
  {q:'What is the name of the AI in 2001: A Space Odyssey?',opts:['Skynet','WOPR','HAL 9000','GLaDOS'],a:2,d:2},
  {q:'Who directed Schindler\'s List?',opts:['Ridley Scott','Steven Spielberg','Francis Ford Coppola','Martin Scorsese'],a:1,d:2},
  {q:'Which film features the quote "Here\'s looking at you, kid"?',opts:['The Maltese Falcon','Casablanca','Citizen Kane','Gone with the Wind'],a:1,d:2},
  {q:'What color is the pill Neo takes in The Matrix?',opts:['Blue','Green','Red','White'],a:2,d:2},
  {q:'Who plays Jack in Titanic?',opts:['Brad Pitt','Johnny Depp','Leonardo DiCaprio','Matt Damon'],a:2,d:2},
  {q:'Which Pixar film features a rat who cooks?',opts:['Up','Ratatouille','Coco','Inside Out'],a:1,d:2},
  {q:'What is Indiana Jones\'s real first name?',opts:['Henry','James','William','Robert'],a:0,d:2},
  {q:'Who directed The Godfather?',opts:['Martin Scorsese','Brian De Palma','Francis Ford Coppola','Sidney Lumet'],a:2,d:2},
  {q:'Which film won the first Best Animated Feature Oscar?',opts:['Toy Story','Shrek','Monsters Inc','Finding Nemo'],a:1,d:3},
  {q:'In The Shining, what is the hotel called?',opts:['Bates Motel','The Overlook','The Stanley','Hill House'],a:1,d:3},
  {q:'Who plays Wolverine in the X-Men films?',opts:['Russell Crowe','Liam Neeson','Hugh Jackman','Christian Bale'],a:2,d:3},
  {q:'What year was the first Toy Story released?',opts:['1993','1994','1995','1996'],a:2,d:3},
  {q:'Which film has the quote "I am your father"?',opts:['A New Hope','The Empire Strikes Back','Return of the Jedi','Revenge of the Sith'],a:1,d:3},
  {q:'Who directed Inception?',opts:['Ridley Scott','Christopher Nolan','Denis Villeneuve','James Cameron'],a:1,d:3},
  {q:'What is the fictional country in Black Panther?',opts:['Zamunda','Wakanda','Genovia','Latveria'],a:1,d:3},
  {q:'Which Studio Ghibli film features a bathhouse?',opts:['My Neighbor Totoro','Spirited Away','Howl\'s Moving Castle','Princess Mononoke'],a:1,d:3},
  {q:'Who played the T-800 in The Terminator?',opts:['Sylvester Stallone','Bruce Willis','Arnold Schwarzenegger','Jean-Claude Van Damme'],a:2,d:3}
],
sports:[
  {q:'Players on court in basketball?',opts:['4','5','6','7'],a:1,d:1},
  {q:'Most FIFA World Cup wins?',opts:['Germany','Argentina','Italy','Brazil'],a:3,d:1},
  {q:'Score after deuce in tennis?',opts:['Love','Advantage','Set point','Match point'],a:1,d:1},
  {q:'Holes in standard golf round?',opts:['9','12','18','21'],a:2,d:1},
  {q:'Which country hosted the 2016 Summer Olympics?',opts:['China','UK','Brazil','Japan'],a:2,d:1},
  {q:'Players in a rugby union team?',opts:['11','13','15','17'],a:2,d:1},
  {q:'The Ryder Cup is contested in which sport?',opts:['Tennis','Golf','Cricket','Polo'],a:1,d:1},
  {q:'Which boxer was known as The Greatest?',opts:['Joe Frazier','Mike Tyson','Muhammad Ali','Sugar Ray Leonard'],a:2,d:1},
  {q:'How many Grand Slam titles did Serena Williams win?',opts:['19','21','23','25'],a:2,d:1},
  {q:'Country with most Olympic gold medals overall?',opts:['Russia','China','Germany','USA'],a:3,d:2},
  {q:'How many players on a baseball team?',opts:['7','8','9','10'],a:2,d:2},
  {q:'The Tour de France is which sport?',opts:['Running','Cycling','Swimming','Triathlon'],a:1,d:2},
  {q:'Which country invented cricket?',opts:['Australia','India','South Africa','England'],a:3,d:2},
  {q:'How long is an Olympic swimming pool in meters?',opts:['25','50','75','100'],a:1,d:2},
  {q:'Which sport uses a shuttlecock?',opts:['Tennis','Squash','Badminton','Table Tennis'],a:2,d:2},
  {q:'In which city were the first modern Olympics held?',opts:['Paris','London','Athens','Rome'],a:2,d:2},
  {q:'How many points is a touchdown worth?',opts:['3','5','6','7'],a:2,d:2},
  {q:'Which country has won the most Cricket World Cups?',opts:['India','West Indies','England','Australia'],a:3,d:2},
  {q:'What does FIFA stand for (first word)?',opts:['Federal','Fédération','Football','Foundation'],a:1,d:3},
  {q:'A regulation soccer match is how many minutes?',opts:['80','85','90','100'],a:2,d:3},
  {q:'Which athlete has the most Olympic medals ever?',opts:['Usain Bolt','Carl Lewis','Michael Phelps','Mark Spitz'],a:2,d:3},
  {q:'In F1, what color flag means danger?',opts:['Red','Blue','Yellow','Black'],a:2,d:3},
  {q:'How many sets to win a men\'s Grand Slam tennis match?',opts:['2','3','4','5'],a:1,d:3},
  {q:'Which sport is played at Wimbledon?',opts:['Golf','Cricket','Tennis','Rugby'],a:2,d:3},
  {q:'The Super Bowl is the final of which league?',opts:['NBA','MLB','NHL','NFL'],a:3,d:3},
  {q:'Which martial art is an Olympic sport from Japan?',opts:['Karate','Kung Fu','Judo','Taekwondo'],a:2,d:3},
  {q:'How many rings are on the Olympic flag?',opts:['4','5','6','7'],a:1,d:3}
],
music:[
  {q:'Strings on a standard guitar?',opts:['4','5','6','7'],a:2,d:1},
  {q:'Band behind Bohemian Rhapsody?',opts:['Led Zeppelin','The Beatles','Queen','The Rolling Stones'],a:2,d:1},
  {q:'BPM stands for?',opts:['Beats Per Minute','Bass Per Measure','Bars Per Movement','Beat Pattern Mode'],a:0,d:1},
  {q:'Instrument with 88 keys?',opts:['Organ','Piano','Harpsichord','Accordion'],a:1,d:1},
  {q:'Who is known as the Queen of Pop?',opts:['Beyoncé','Rihanna','Madonna','Lady Gaga'],a:2,d:1},
  {q:'Best-selling album of all time?',opts:['Back in Black','Thriller','Dark Side of the Moon','Hotel California'],a:1,d:1},
  {q:'Freddie Mercury was lead singer of which band?',opts:['Aerosmith','KISS','Queen','Led Zeppelin'],a:2,d:1},
  {q:'How many strings does a violin have?',opts:['3','4','5','6'],a:1,d:1},
  {q:'What nationality was Beethoven?',opts:['Austrian','French','German','Dutch'],a:2,d:1},
  {q:'Who released the album Thriller in 1982?',opts:['Prince','Michael Jackson','David Bowie','Elton John'],a:1,d:2},
  {q:'Which instrument does a drummer play?',opts:['Percussion','Strings','Brass','Woodwind'],a:0,d:2},
  {q:'Who is known as the King of Rock and Roll?',opts:['Chuck Berry','Elvis Presley','Little Richard','Jerry Lee Lewis'],a:1,d:2},
  {q:'Stairway to Heaven was by which band?',opts:['Pink Floyd','Deep Purple','Led Zeppelin','Black Sabbath'],a:2,d:2},
  {q:'What genre did Bob Marley popularize?',opts:['Ska','Reggae','Calypso','Dancehall'],a:1,d:2},
  {q:'How many members were in The Beatles?',opts:['3','4','5','6'],a:1,d:2},
  {q:'Which instrument is Yo-Yo Ma famous for?',opts:['Violin','Viola','Cello','Double Bass'],a:2,d:2},
  {q:'Who sang "Like a Rolling Stone"?',opts:['Bob Dylan','Bruce Springsteen','Neil Young','Tom Petty'],a:0,d:2},
  {q:'What does DJ stand for?',opts:['Digital Jockey','Disc Jockey','Dance Jammer','Drop Juggler'],a:1,d:2},
  {q:'Which country does K-pop come from?',opts:['Japan','China','South Korea','Thailand'],a:2,d:3},
  {q:'Who composed The Four Seasons?',opts:['Mozart','Bach','Vivaldi','Handel'],a:2,d:3},
  {q:'What woodwind instrument is black and has a single reed?',opts:['Oboe','Flute','Bassoon','Clarinet'],a:3,d:3},
  {q:'Which rapper is known as Slim Shady?',opts:['50 Cent','Dr. Dre','Eminem','Snoop Dogg'],a:2,d:3},
  {q:'Billie Eilish\'s debut album was called?',opts:['Happier Than Ever','When We All Fall Asleep','Don\'t Smile at Me','Bad Guy'],a:1,d:3},
  {q:'What time signature is a waltz in?',opts:['2/4','3/4','4/4','6/8'],a:1,d:3},
  {q:'Which festival is held in the Nevada desert?',opts:['Coachella','Glastonbury','Burning Man','Lollapalooza'],a:2,d:3},
  {q:'Who sang "Imagine"?',opts:['Paul McCartney','George Harrison','John Lennon','Ringo Starr'],a:2,d:3}
],
tech:[
  {q:'HTML stands for?',opts:['Hyper Text Markup Language','High Tech Modern Language','Hyper Transfer Media Link','Home Tool Markup Language'],a:0,d:1},
  {q:'Company that created the iPhone?',opts:['Samsung','Google','Apple','Microsoft'],a:2,d:1},
  {q:'Binary of decimal 10?',opts:['1000','1010','1100','1001'],a:1,d:1},
  {q:'Co-founder of Apple with Steve Jobs?',opts:['Bill Gates','Steve Wozniak','Larry Page','Elon Musk'],a:1,d:1},
  {q:'CPU stands for?',opts:['Central Processing Unit','Computer Power Unit','Core Processing Utility','Central Program Unit'],a:0,d:1},
  {q:'Which company owns YouTube?',opts:['Meta','Microsoft','Amazon','Google'],a:3,d:1},
  {q:'Language known as the language of the web?',opts:['Python','Java','JavaScript','C++'],a:2,d:1},
  {q:'Year the first iPhone was released?',opts:['2005','2006','2007','2008'],a:2,d:1},
  {q:'What does Wi-Fi stand for?',opts:['Wireless Fidelity','Wide Frequency','Wireless Frequency Interface','It is a brand name'],a:3,d:1},
  {q:'Which company made the first commercial GPS device?',opts:['Garmin','TomTom','Magellan','Nokia'],a:0,d:2},
  {q:'What does RAM stand for?',opts:['Random Access Memory','Read Always Memory','Run Application Mode','Rapid Auto Memory'],a:0,d:2},
  {q:'Who founded Amazon?',opts:['Elon Musk','Jeff Bezos','Bill Gates','Mark Zuckerberg'],a:1,d:2},
  {q:'What programming language has a coffee cup logo?',opts:['Python','C#','Java','Ruby'],a:2,d:2},
  {q:'How many bits in a byte?',opts:['4','6','8','16'],a:2,d:2},
  {q:'What does USB stand for?',opts:['Universal Serial Bus','Ultra Speed Buffer','Unified System Bridge','Universal System Byte'],a:0,d:2},
  {q:'Which company makes the Android OS?',opts:['Apple','Samsung','Google','Microsoft'],a:2,d:2},
  {q:'What year was Facebook founded?',opts:['2002','2004','2006','2008'],a:1,d:2},
  {q:'The first computer programmer is often considered to be?',opts:['Alan Turing','Grace Hopper','Ada Lovelace','Charles Babbage'],a:2,d:2},
  {q:'What does SSD stand for?',opts:['Super Speed Disk','Solid State Drive','System Storage Device','Serial Signal Data'],a:1,d:3},
  {q:'Which company created Windows?',opts:['Apple','IBM','Google','Microsoft'],a:3,d:3},
  {q:'What does API stand for?',opts:['Application Programming Interface','Auto Program Input','Advanced Protocol Integration','Applied Processing Instance'],a:0,d:3},
  {q:'Bitcoin was created by whom?',opts:['Vitalik Buterin','Satoshi Nakamoto','Elon Musk','Tim Berners-Lee'],a:1,d:3},
  {q:'What does GPU stand for?',opts:['General Processing Unit','Graphics Processing Unit','Global Power Unit','Grid Pixel Utility'],a:1,d:3},
  {q:'Which company makes the PlayStation?',opts:['Nintendo','Microsoft','Sony','Sega'],a:2,d:3},
  {q:'What language is most used for iOS apps?',opts:['Java','Kotlin','Swift','C++'],a:2,d:3},
  {q:'Who invented the World Wide Web?',opts:['Bill Gates','Steve Jobs','Tim Berners-Lee','Vint Cerf'],a:2,d:3},
  {q:'What is the most popular programming language in 2024?',opts:['Java','Python','JavaScript','C++'],a:1,d:3}
],
space:[
  {q:'The Red Planet?',opts:['Venus','Jupiter','Mars','Saturn'],a:2,d:1},
  {q:'Sunlight travel time to Earth?',opts:['2 minutes','8 minutes','20 minutes','1 hour'],a:1,d:1},
  {q:'Name of our galaxy?',opts:['Andromeda','Triangulum','Milky Way','Whirlpool'],a:2,d:1},
  {q:'First Moon landing mission?',opts:['Apollo 9','Apollo 10','Apollo 11','Apollo 12'],a:2,d:1},
  {q:'Which planet has the most moons?',opts:['Jupiter','Saturn','Uranus','Neptune'],a:1,d:1},
  {q:'Closest star to Earth?',opts:['Betelgeuse','Sirius','Proxima Centauri','Alpha Centauri A'],a:2,d:1},
  {q:'First artificial satellite in space?',opts:['Explorer 1','Vostok 1','Sputnik 1','Luna 1'],a:2,d:1},
  {q:'How long does Earth take to orbit the Sun?',opts:['265 days','365 days','400 days','465 days'],a:1,d:1},
  {q:'Which planet rotates on its side?',opts:['Neptune','Venus','Uranus','Saturn'],a:2,d:1},
  {q:'A light-year is a measure of?',opts:['Time','Speed','Distance','Brightness'],a:2,d:2},
  {q:'Largest planet in our solar system?',opts:['Saturn','Neptune','Jupiter','Uranus'],a:2,d:2},
  {q:'What is the hottest planet?',opts:['Mercury','Venus','Mars','Jupiter'],a:1,d:2},
  {q:'Which planet is known for its rings?',opts:['Jupiter','Neptune','Uranus','Saturn'],a:3,d:2},
  {q:'First woman in space?',opts:['Sally Ride','Mae Jemison','Valentina Tereshkova','Peggy Whitson'],a:2,d:2},
  {q:'How many planets in our solar system?',opts:['7','8','9','10'],a:1,d:2},
  {q:'What is a supernova?',opts:['A comet','An exploding star','A black hole','A galaxy'],a:1,d:2},
  {q:'Which space agency launched the Hubble telescope?',opts:['ESA','Roscosmos','NASA','JAXA'],a:2,d:2},
  {q:'Pluto was reclassified as a dwarf planet in?',opts:['2000','2003','2006','2009'],a:2,d:2},
  {q:'What is the Sun mainly made of?',opts:['Helium','Oxygen','Iron','Hydrogen'],a:3,d:3},
  {q:'Which rover landed on Mars in 2021?',opts:['Curiosity','Opportunity','Spirit','Perseverance'],a:3,d:3},
  {q:'The International Space Station orbits Earth every?',opts:['45 minutes','90 minutes','3 hours','12 hours'],a:1,d:3},
  {q:'What force keeps planets in orbit?',opts:['Magnetism','Friction','Gravity','Inertia'],a:2,d:3},
  {q:'Which planet has the Great Red Spot?',opts:['Mars','Saturn','Neptune','Jupiter'],a:3,d:3},
  {q:'What is the closest planet to the Sun?',opts:['Venus','Mars','Mercury','Earth'],a:2,d:3},
  {q:'A black hole is formed from a collapsed?',opts:['Planet','Moon','Star','Asteroid'],a:2,d:3},
  {q:'What is the name of Mars\'s largest moon?',opts:['Europa','Titan','Phobos','Ganymede'],a:2,d:3}
],
art:[
  {q:'Painter of the Mona Lisa?',opts:['Michelangelo','Raphael','Leonardo da Vinci','Caravaggio'],a:2,d:1},
  {q:'Author of 1984?',opts:['Aldous Huxley','George Orwell','Ray Bradbury','H.G. Wells'],a:1,d:1},
  {q:'City of the Louvre museum?',opts:['Rome','Madrid','London','Paris'],a:3,d:1},
  {q:'Author of Romeo and Juliet?',opts:['Charles Dickens','Oscar Wilde','William Shakespeare','John Keats'],a:2,d:1},
  {q:'Who wrote Don Quixote?',opts:['Lope de Vega','Miguel de Cervantes','Gustavo Bécquer','Francisco de Quevedo'],a:1,d:1},
  {q:'Salvador Dalí belonged to which art movement?',opts:['Cubism','Impressionism','Surrealism','Expressionism'],a:2,d:1},
  {q:'Who sculpted The Thinker?',opts:['Michelangelo','Auguste Rodin','Donatello','Bernini'],a:1,d:1},
  {q:'In which museum is the Mona Lisa displayed?',opts:['The Met','The Prado','The Louvre','The Uffizi'],a:2,d:1},
  {q:'Who wrote Crime and Punishment?',opts:['Leo Tolstoy','Ivan Turgenev','Anton Chekhov','Fyodor Dostoevsky'],a:3,d:1},
  {q:'Which Dutch painter cut off his own ear?',opts:['Vermeer','Rembrandt','Van Gogh','Mondrian'],a:2,d:2},
  {q:'Who wrote Pride and Prejudice?',opts:['Charlotte Brontë','Jane Austen','Mary Shelley','Emily Brontë'],a:1,d:2},
  {q:'Which art movement did Monet pioneer?',opts:['Surrealism','Cubism','Impressionism','Realism'],a:2,d:2},
  {q:'Who wrote The Great Gatsby?',opts:['Ernest Hemingway','F. Scott Fitzgerald','John Steinbeck','Mark Twain'],a:1,d:2},
  {q:'The Starry Night was painted by?',opts:['Monet','Picasso','Van Gogh','Cézanne'],a:2,d:2},
  {q:'Who wrote Hamlet?',opts:['Christopher Marlowe','Ben Jonson','William Shakespeare','John Milton'],a:2,d:2},
  {q:'Which artist is famous for pop art soup cans?',opts:['Roy Lichtenstein','Jasper Johns','Andy Warhol','Keith Haring'],a:2,d:2},
  {q:'Author of To Kill a Mockingbird?',opts:['Harper Lee','Truman Capote','Toni Morrison','Maya Angelou'],a:0,d:2},
  {q:'Which Renaissance artist sculpted David?',opts:['Donatello','Raphael','Michelangelo','Bernini'],a:2,d:2},
  {q:'Who wrote One Hundred Years of Solitude?',opts:['Pablo Neruda','Isabel Allende','Gabriel García Márquez','Jorge Luis Borges'],a:2,d:3},
  {q:'The Scream was painted by?',opts:['Gustav Klimt','Egon Schiele','Edvard Munch','Wassily Kandinsky'],a:2,d:3},
  {q:'Who wrote The Odyssey?',opts:['Virgil','Sophocles','Homer','Plato'],a:2,d:3},
  {q:'Guernica was painted by?',opts:['Dalí','Picasso','Miró','Goya'],a:1,d:3},
  {q:'Who wrote Frankenstein?',opts:['Bram Stoker','Mary Shelley','Edgar Allan Poe','H.G. Wells'],a:1,d:3},
  {q:'Which art movement did Picasso co-found?',opts:['Surrealism','Impressionism','Cubism','Dadaism'],a:2,d:3},
  {q:'Who painted The Birth of Venus?',opts:['Raphael','Titian','Botticelli','Leonardo'],a:2,d:3},
  {q:'Author of The Lord of the Flies?',opts:['George Orwell','Aldous Huxley','William Golding','Ray Bradbury'],a:2,d:3}
],
games:[
  {q:'Zelda series by which company?',opts:['Sega','Sony','Nintendo','Capcom'],a:2,d:1},
  {q:'Year first PlayStation released?',opts:['1992','1994','1996','1998'],a:1,d:1},
  {q:'Minecraft is a type of?',opts:['FPS','RPG','Sandbox','MOBA'],a:2,d:1},
  {q:'Character who eats dots in a maze?',opts:['Pac-Man','Donkey Kong','Frogger','Q*bert'],a:0,d:1},
  {q:'Master Chief is from which game?',opts:['Gears of War','Halo','Doom','Call of Duty'],a:1,d:1},
  {q:'What animal is Sonic?',opts:['Fox','Rabbit','Hedgehog','Cat'],a:2,d:1},
  {q:'Which game features building with blocks?',opts:['Fortnite','Roblox','Minecraft','Terraria'],a:2,d:1},
  {q:'Which company makes Mario games?',opts:['Sega','Nintendo','Sony','Microsoft'],a:1,d:1},
  {q:'GTA stands for?',opts:['Grand Theft Auto','Great Tactical Arena','Game Tournament Alliance','Global Task Agency'],a:0,d:1},
  {q:'Year Fortnite Battle Royale launched?',opts:['2015','2016','2017','2018'],a:2,d:2},
  {q:'What is the best-selling video game ever?',opts:['GTA V','Tetris','Minecraft','Wii Sports'],a:2,d:2},
  {q:'Which game features a character named Link?',opts:['Final Fantasy','Zelda','Metroid','Fire Emblem'],a:1,d:2},
  {q:'What does RPG stand for in gaming?',opts:['Real Player Game','Role Playing Game','Rapid Play Genre','Random Puzzle Grid'],a:1,d:2},
  {q:'Which game has a Battle Royale mode with a storm?',opts:['PUBG','Apex Legends','Fortnite','Warzone'],a:2,d:2},
  {q:'Who is Mario\'s brother?',opts:['Wario','Toad','Luigi','Yoshi'],a:2,d:2},
  {q:'Which console was released in 2020?',opts:['Nintendo Switch','Xbox One','PS5','PS4'],a:2,d:2},
  {q:'Kratos is the main character of?',opts:['Devil May Cry','Bayonetta','God of War','Dante\'s Inferno'],a:2,d:2},
  {q:'What color is Pikachu?',opts:['Red','Blue','Green','Yellow'],a:3,d:2},
  {q:'Which game popularized battle royale genre?',opts:['Fortnite','H1Z1','PUBG','Apex Legends'],a:2,d:3},
  {q:'Elden Ring was made by?',opts:['Capcom','Bethesda','FromSoftware','Square Enix'],a:2,d:3},
  {q:'What is the currency in Fortnite?',opts:['Robux','Gems','V-Bucks','Credits'],a:2,d:3},
  {q:'Portal is famous for which device?',opts:['Gravity Gun','Portal Gun','Grapple Hook','Time Machine'],a:1,d:3},
  {q:'Which game features the Creeper enemy?',opts:['Terraria','Roblox','Minecraft','Fortnite'],a:2,d:3},
  {q:'The Last of Us is set during a?',opts:['War','Zombie apocalypse','Alien invasion','Pandemic'],a:3,d:3},
  {q:'Which company makes the Xbox?',opts:['Sony','Nintendo','Microsoft','Sega'],a:2,d:3},
  {q:'How many Pokémon were in the original games?',opts:['100','120','150','151'],a:3,d:3}
],
mythology:[
  {q:'Greek god of the sea?',opts:['Zeus','Ares','Poseidon','Apollo'],a:2,d:1},
  {q:'Norse god of thunder?',opts:['Odin','Loki','Freya','Thor'],a:3,d:1},
  {q:'Medusa turns people to?',opts:['Gold','Stone','Ice','Dust'],a:1,d:1},
  {q:'Labyrinth creature of Crete?',opts:['Sphinx','Minotaur','Hydra','Cerberus'],a:1,d:1},
  {q:'Egyptian god of the dead?',opts:['Ra','Horus','Anubis','Osiris'],a:2,d:1},
  {q:'Who opened the forbidden box?',opts:['Athena','Persephone','Pandora','Aphrodite'],a:2,d:1},
  {q:'How many heads does the Hydra grow back?',opts:['1','2','3','4'],a:1,d:1},
  {q:'Which hero completed 12 labors?',opts:['Perseus','Achilles','Hercules','Theseus'],a:2,d:1},
  {q:'Odin\'s eight-legged horse?',opts:['Fenrir','Jörmungandr','Sleipnir','Huginn'],a:2,d:1},
  {q:'River of the dead in Greek myth?',opts:['Lethe','Acheron','Styx','Phlegethon'],a:2,d:2},
  {q:'Greek goddess of wisdom?',opts:['Hera','Artemis','Athena','Aphrodite'],a:2,d:2},
  {q:'Who killed Medusa?',opts:['Theseus','Odysseus','Perseus','Achilles'],a:2,d:2},
  {q:'What animal pulled Thor\'s chariot?',opts:['Wolves','Horses','Goats','Bears'],a:2,d:2},
  {q:'Greek god of the underworld?',opts:['Ares','Hermes','Hades','Dionysus'],a:2,d:2},
  {q:'Loki is the Norse god of?',opts:['War','Wisdom','Mischief','Thunder'],a:2,d:2},
  {q:'What did King Midas turn things into?',opts:['Silver','Gold','Stone','Glass'],a:1,d:2},
  {q:'Icarus flew too close to what?',opts:['The Moon','The Sea','The Sun','The Stars'],a:2,d:2},
  {q:'Who ferried souls across the River Styx?',opts:['Hades','Hermes','Charon','Cerberus'],a:2,d:2},
  {q:'The Phoenix rises from what?',opts:['Water','Ice','Ashes','Sand'],a:2,d:3},
  {q:'Excalibur belonged to which king?',opts:['Charlemagne','Arthur','Richard','Leonidas'],a:1,d:3},
  {q:'How many heads does Cerberus have?',opts:['1','2','3','5'],a:2,d:3},
  {q:'Norse end of the world is called?',opts:['Valhalla','Ragnarök','Asgard','Niflheim'],a:1,d:3},
  {q:'Who was the Greek hero of the Trojan War?',opts:['Perseus','Theseus','Achilles','Heracles'],a:2,d:3},
  {q:'Egyptian god with a falcon head?',opts:['Anubis','Osiris','Horus','Thoth'],a:2,d:3},
  {q:'What creature is half man, half horse?',opts:['Minotaur','Satyr','Centaur','Faun'],a:2,d:3},
  {q:'Mjolnir is the weapon of which god?',opts:['Odin','Loki','Freyr','Thor'],a:3,d:3}
],
harrypotter:[
  {q:'Harry\'s position in Quidditch?',opts:['Chaser','Keeper','Beater','Seeker'],a:3,d:1},
  {q:'What is a Horcrux?',opts:['A spell','A soul container','A potion','A creature'],a:1,d:1},
  {q:'Hogwarts headmaster in book 1?',opts:['Snape','McGonagall','Dumbledore','Hagrid'],a:2,d:1},
  {q:'How many Deathly Hallows exist?',opts:['2','3','4','7'],a:1,d:1},
  {q:'What animal is Hedwig?',opts:['Cat','Toad','Owl','Rat'],a:2,d:1},
  {q:'Platform for the Hogwarts Express?',opts:['7½','8¾','9¾','10½'],a:2,d:1},
  {q:'Who is the Half-Blood Prince?',opts:['Voldemort','Dumbledore','Snape','Draco'],a:2,d:1},
  {q:'How many books in the HP series?',opts:['5','6','7','8'],a:2,d:1},
  {q:'Which house values bravery?',opts:['Slytherin','Ravenclaw','Hufflepuff','Gryffindor'],a:3,d:1},
  {q:'Voldemort\'s real first name?',opts:['Marvolo','Tom','Salazar','Lucius'],a:1,d:2},
  {q:'What is the core of Harry\'s wand?',opts:['Dragon heartstring','Unicorn hair','Phoenix feather','Thestral tail'],a:2,d:2},
  {q:'Who teaches Potions in Harry\'s first year?',opts:['McGonagall','Snape','Flitwick','Quirrell'],a:1,d:2},
  {q:'What shape is Harry\'s scar?',opts:['Circle','Star','Lightning bolt','Crescent'],a:2,d:2},
  {q:'What is the name of the Weasley house?',opts:['The Hollow','Shell Cottage','The Burrow','Grimmauld Place'],a:2,d:2},
  {q:'Which spell disarms an opponent?',opts:['Stupefy','Expelliarmus','Protego','Reducto'],a:1,d:2},
  {q:'What creature guards the Philosopher\'s Stone?',opts:['Dragon','Troll','Three-headed dog','Giant spider'],a:2,d:2},
  {q:'What is Hermione\'s patronus?',opts:['Horse','Cat','Otter','Hare'],a:2,d:2},
  {q:'Who gives Harry the invisibility cloak?',opts:['Sirius','Hagrid','Dumbledore','Snape'],a:2,d:2},
  {q:'What position does Ron play in Quidditch?',opts:['Chaser','Seeker','Beater','Keeper'],a:3,d:3},
  {q:'Which subject does Professor Binns teach?',opts:['Divination','Potions','History of Magic','Herbology'],a:2,d:3},
  {q:'What is the name of Hagrid\'s dragon?',opts:['Norberta','Fang','Buckbeak','Aragog'],a:0,d:3},
  {q:'Which spell produces light?',opts:['Nox','Lumos','Accio','Alohomora'],a:1,d:3},
  {q:'What is the Marauder\'s Map phrase?',opts:['Open Sesame','I solemnly swear I am up to no good','Mischief managed','Reveal your secrets'],a:1,d:3},
  {q:'Who kills Dumbledore?',opts:['Voldemort','Draco','Bellatrix','Snape'],a:3,d:3},
  {q:'What form does Harry\'s patronus take?',opts:['Wolf','Phoenix','Stag','Lion'],a:2,d:3},
  {q:'Dobby is what kind of creature?',opts:['Goblin','Gnome','House-elf','Pixie'],a:2,d:3}
],
starwars:[
  {q:'Darth Vader\'s real name?',opts:['Luke Skywalker','Han Solo','Anakin Skywalker','Obi-Wan Kenobi'],a:2,d:1},
  {q:'Yoda\'s lightsaber color?',opts:['Blue','Red','Purple','Green'],a:3,d:1},
  {q:'Han Solo\'s ship?',opts:['X-Wing','TIE Fighter','Millennium Falcon','Star Destroyer'],a:2,d:1},
  {q:'Planet destroyed by Death Star?',opts:['Tatooine','Alderaan','Naboo','Hoth'],a:1,d:1},
  {q:'Chewbacca is which species?',opts:['Ewok','Wookiee','Gungan','Jawa'],a:1,d:1},
  {q:'Episode V subtitle?',opts:['A New Hope','The Empire Strikes Back','Return of the Jedi','The Phantom Menace'],a:1,d:1},
  {q:'Who trained Luke Skywalker?',opts:['Mace Windu','Qui-Gon Jinn','Obi-Wan & Yoda','Count Dooku'],a:2,d:1},
  {q:'Color of Mace Windu\'s lightsaber?',opts:['Green','Blue','Red','Purple'],a:3,d:1},
  {q:'Bounty hunter who captured Han Solo?',opts:['Greedo','Boba Fett','Jango Fett','Bossk'],a:1,d:1},
  {q:'What are the evil Sith known for?',opts:['Blue lightsabers','Force healing','Rule of Two','Jedi Council'],a:2,d:2},
  {q:'Which planet is Luke from?',opts:['Naboo','Coruscant','Tatooine','Dagobah'],a:2,d:2},
  {q:'Who is Rey\'s grandfather?',opts:['Obi-Wan','Luke','Han Solo','Palpatine'],a:3,d:2},
  {q:'What species is Jabba?',opts:['Hutt','Rodian','Twi\'lek','Wookiee'],a:0,d:2},
  {q:'Who said "Do or do not, there is no try"?',opts:['Obi-Wan','Luke','Yoda','Mace Windu'],a:2,d:2},
  {q:'What is the Jedi weapon?',opts:['Blaster','Lightsaber','Bowcaster','Vibroblade'],a:1,d:2},
  {q:'Who killed Han Solo?',opts:['Boba Fett','Snoke','Kylo Ren','Palpatine'],a:2,d:2},
  {q:'The Clone Army was based on which bounty hunter?',opts:['Boba Fett','Cad Bane','Jango Fett','Bossk'],a:2,d:2},
  {q:'What is Baby Yoda\'s actual name?',opts:['Yaddle','Grogu','Yodel','Grog'],a:1,d:2},
  {q:'Which droid carries the Death Star plans?',opts:['C-3PO','BB-8','R2-D2','K-2SO'],a:2,d:3},
  {q:'Darth Sidious is also known as?',opts:['Dooku','Maul','Palpatine','Snoke'],a:2,d:3},
  {q:'The forest moon of Endor is home to?',opts:['Jawas','Ewoks','Gungans','Wookiees'],a:1,d:3},
  {q:'What color is a Sith lightsaber?',opts:['Blue','Green','Red','Yellow'],a:2,d:3},
  {q:'Who froze Han Solo in carbonite?',opts:['Jabba','Boba Fett','Darth Vader','Lando'],a:2,d:3},
  {q:'Princess Leia is from which planet?',opts:['Coruscant','Naboo','Alderaan','Bespin'],a:2,d:3},
  {q:'What type of trooper wears white armor?',opts:['Clone trooper','Stormtrooper','Death trooper','Scout trooper'],a:1,d:3},
  {q:'Which ship made the Kessel Run in 12 parsecs?',opts:['X-Wing','Slave I','Millennium Falcon','Naboo Starfighter'],a:2,d:3}
],
lotr:[
  {q:'Who carries the One Ring to Mordor?',opts:['Aragorn','Gandalf','Frodo','Legolas'],a:2,d:1},
  {q:'Gandalf\'s horse?',opts:['Asfaloth','Shadowfax','Bill the Pony','Roheryn'],a:1,d:1},
  {q:'How many rings for the Elven-kings?',opts:['1','3','7','9'],a:1,d:1},
  {q:'What is Gollum\'s real name?',opts:['Bilbo','Déagol','Sméagol','Faramir'],a:2,d:1},
  {q:'Legolas is which race?',opts:['Human','Dwarf','Elf','Hobbit'],a:2,d:1},
  {q:'What is the name of Aragorn\'s sword?',opts:['Glamdring','Sting','Andúril','Orcrist'],a:2,d:1},
  {q:'Who says "You shall not pass"?',opts:['Aragorn','Gandalf','Elrond','Saruman'],a:1,d:1},
  {q:'Mordor\'s volcanic mountain?',opts:['Minas Tirith','Mount Doom','Weathertop','Isengard'],a:1,d:1},
  {q:'How many members in the Fellowship?',opts:['7','8','9','10'],a:2,d:1},
  {q:'Who kills the Witch-king?',opts:['Gandalf','Aragorn','Éowyn','Legolas'],a:2,d:2},
  {q:'What is the Shire?',opts:['An Elven city','Hobbit homeland','Dwarf mines','A human kingdom'],a:1,d:2},
  {q:'Who created the One Ring?',opts:['Morgoth','Saruman','Sauron','Celebrimbor'],a:2,d:2},
  {q:'Gimli is which race?',opts:['Elf','Hobbit','Human','Dwarf'],a:3,d:2},
  {q:'What gift does Galadriel give Frodo?',opts:['A sword','A light','A cloak','A shield'],a:1,d:2},
  {q:'Who is the king of Rohan?',opts:['Denethor','Théoden','Faramir','Elrond'],a:1,d:2},
  {q:'Bilbo\'s sword is called?',opts:['Glamdring','Orcrist','Sting','Andúril'],a:2,d:2},
  {q:'Which tower does Saruman live in?',opts:['Barad-dûr','Minas Tirith','Orthanc','Minas Morgul'],a:2,d:2},
  {q:'What creature does Gandalf fight in Moria?',opts:['Dragon','Troll','Balrog','Warg'],a:2,d:2},
  {q:'Sam\'s full first name is?',opts:['Samuel','Samwell','Samwise','Sampson'],a:2,d:3},
  {q:'How many rings were made for mortal men?',opts:['3','5','7','9'],a:3,d:3},
  {q:'Who destroys the One Ring?',opts:['Frodo','Sam','Gollum','Aragorn'],a:2,d:3},
  {q:'What is Legolas\'s weapon of choice?',opts:['Sword','Axe','Bow','Spear'],a:2,d:3},
  {q:'Which city is the capital of Gondor?',opts:['Edoras','Rivendell','Minas Tirith','Osgiliath'],a:2,d:3},
  {q:'What does the Eye of Sauron sit atop?',opts:['Mount Doom','Barad-dûr','Orthanc','Minas Morgul'],a:1,d:3},
  {q:'Who says "My precious"?',opts:['Frodo','Bilbo','Sauron','Gollum'],a:3,d:3},
  {q:'What are the tree creatures called?',opts:['Elves','Orcs','Ents','Wargs'],a:2,d:3}
],
got:[
  {q:'Motto of House Stark?',opts:['Fire and Blood','Ours is the Fury','Winter is Coming','We Do Not Sow'],a:2,d:1},
  {q:'Who sits on the Iron Throne at the start?',opts:['Joffrey Baratheon','Robert Baratheon','Cersei Lannister','Ned Stark'],a:1,d:1},
  {q:'Who killed Joffrey Baratheon?',opts:['Tyrion Lannister','Olenna Tyrell','Sansa Stark','Littlefinger'],a:1,d:1},
  {q:'Name of Arya Stark\'s sword?',opts:['Longclaw','Needle','Ice','Oathkeeper'],a:1,d:1},
  {q:'Which episode is known as The Red Wedding?',opts:['S2E9','S3E7','S3E9','S4E2'],a:2,d:1},
  {q:'Who is Jon Snow\'s biological father?',opts:['Ned Stark','Robert Baratheon','Rhaegar Targaryen','Stannis Baratheon'],a:2,d:1},
  {q:'Name of the castle at the Wall?',opts:['Winterfell','Castle Black','Hardhome','Eastwatch'],a:1,d:1},
  {q:'Who plays Tyrion Lannister?',opts:['Kit Harington','Nikolaj Coster-Waldau','Peter Dinklage','Liam Cunningham'],a:2,d:1},
  {q:'What does Valar Morghulis mean?',opts:['Fire and Blood','All men must die','Night gathers','What is dead may never die'],a:1,d:1},
  {q:'What are Daenerys\'s three dragons called?',opts:['Smaug, Fafnir, Glaurung','Drogon, Rhaegal, Viserion','Balerion, Vhagar, Meraxes','Jon, Aegon, Aemon'],a:1,d:2},
  {q:'Which family rules Casterly Rock?',opts:['Stark','Tyrell','Baratheon','Lannister'],a:3,d:2},
  {q:'What is the Wall made of?',opts:['Stone','Wood','Ice','Steel'],a:2,d:2},
  {q:'Who is Hodor?',opts:['A knight','Bran\'s carrier','A wildling','A Maester'],a:1,d:2},
  {q:'Daenerys is also known as?',opts:['The Red Woman','Mother of Dragons','Queen of Thorns','Lady Stoneheart'],a:1,d:2},
  {q:'Which city is across the Narrow Sea?',opts:['Pentos','Winterfell','King\'s Landing','Oldtown'],a:0,d:2},
  {q:'What creatures are north of the Wall?',opts:['Dragons','Giants only','White Walkers','Direwolves only'],a:2,d:2},
  {q:'Jon Snow\'s direwolf is named?',opts:['Grey Wind','Summer','Nymeria','Ghost'],a:3,d:2},
  {q:'Who pushes Bran from the tower?',opts:['Cersei','The Hound','Jaime','Joffrey'],a:2,d:2},
  {q:'Motto of House Lannister?',opts:['Ours is the Fury','Growing Strong','Hear Me Roar','Fire and Blood'],a:2,d:3},
  {q:'Which character has a face-changing ability?',opts:['Sansa','Arya','Bran','Cersei'],a:1,d:3},
  {q:'What is wildfire?',opts:['A dragon','A green explosive','A sword','A poison'],a:1,d:3},
  {q:'Who rules the Iron Islands?',opts:['Boltons','Greyjoys','Martells','Tarlys'],a:1,d:3},
  {q:'The Night King is the leader of?',opts:['The Wildlings','The Dothraki','The White Walkers','The Ironborn'],a:2,d:3},
  {q:'What does Bran become by the end?',opts:['King','Hand of the King','Night\'s Watch','Maester'],a:0,d:3},
  {q:'Who forged Arya\'s weapon in Season 8?',opts:['Tywin','The Hound','Gendry','Davos'],a:2,d:3},
  {q:'Which house has a rose as its sigil?',opts:['Martell','Tully','Tyrell','Arryn'],a:2,d:3}
],
breakingbad:[
  {q:'Walter White\'s alias?',opts:['The Cook','El Diablo','Heisenberg','Señor Blanco'],a:2,d:1},
  {q:'Subject Walter White teaches?',opts:['Biology','Chemistry','Physics','Maths'],a:1,d:1},
  {q:'Color of Walter\'s famous meth?',opts:['White','Yellow','Blue','Clear'],a:2,d:1},
  {q:'Fast food chain Gus Fring owns?',opts:['Taco Sal','Los Pollos Hermanos','Salamancas','Madrigals'],a:1,d:1},
  {q:'Saul Goodman\'s real name?',opts:['James McGill','Howard Hamlin','Chuck McGill','Kim Wexler'],a:0,d:1},
  {q:'Main antagonist of season 4?',opts:['Tuco Salamanca','Juan Bolsa','Gus Fring','Don Eladio'],a:2,d:1},
  {q:'What car does Walt buy himself as a treat?',opts:['Pontiac Aztek','Chrysler 300','Dodge Challenger','BMW 3 Series'],a:2,d:1},
  {q:'How many seasons does Breaking Bad have?',opts:['4','5','6','7'],a:1,d:1},
  {q:'Jesse Pinkman\'s partner killed early on?',opts:['Combo','Badger','Emilio','Skinny Pete'],a:2,d:1},
  {q:'What is the name of Walter\'s lawyer?',opts:['Mike Ehrmantraut','Saul Goodman','Hector Salamanca','Gale Boetticher'],a:1,d:2},
  {q:'What is Walter\'s wife\'s name?',opts:['Marie','Skyler','Jane','Lydia'],a:1,d:2},
  {q:'Hank Schrader works for which agency?',opts:['FBI','CIA','DEA','ATF'],a:2,d:2},
  {q:'What is the RV used for?',opts:['Living','Cooking meth','Storage','Surveillance'],a:1,d:2},
  {q:'Jesse often says which word?',opts:['Dude','Bro','Yo','Man'],a:2,d:2},
  {q:'What state is the show set in?',opts:['Arizona','Texas','Nevada','New Mexico'],a:3,d:2},
  {q:'Who runs the car wash?',opts:['Jesse','Skyler','Walt Jr.','Walter'],a:3,d:2},
  {q:'What disability does Walt Jr. have?',opts:['Blindness','Deafness','Cerebral palsy','Autism'],a:2,d:2},
  {q:'Gus Fring dies from a?',opts:['Gunshot','Poison','Bomb','Stabbing'],a:2,d:2},
  {q:'What does the Lily of the Valley symbolize?',opts:['Death','Walt poisoned Brock','Jesse\'s innocence','Gus\'s revenge'],a:1,d:3},
  {q:'Where does Hank find evidence against Walt?',opts:['The car wash','Walt\'s lab','The bathroom','Jesse\'s house'],a:2,d:3},
  {q:'What is Mike\'s profession?',opts:['Lawyer','Fixer/hitman','Accountant','Chemist'],a:1,d:3},
  {q:'Todd works for which group?',opts:['Cartel','DEA','Neo-Nazis','Madrigal'],a:2,d:3},
  {q:'What does Walter say "I am" in the final season?',opts:['The cook','The danger','The one who knocks','Heisenberg'],a:2,d:3},
  {q:'What happens to Jesse at the end?',opts:['He dies','He goes to prison','He escapes','He takes over'],a:2,d:3},
  {q:'Walter\'s cancer affects which organ?',opts:['Brain','Liver','Lungs','Stomach'],a:2,d:3},
  {q:'What element symbol represents the show?',opts:['Br & Ba','He & Br','W & W','Cr & Ys'],a:0,d:3}
]};


/* ═══════ PERSISTENT STATS (window.storage) ═══════ */
const ACHIEVEMENTS=[
  {id:'first_win',icon:'🏆',name:'First Victory',desc:'Win your first game',check:s=>s.wins>=1},
  {id:'five_wins',icon:'👑',name:'Serial Champion',desc:'Win 5 games',check:s=>s.wins>=5},
  {id:'ten_games',icon:'🎮',name:'Dedicated Player',desc:'Play 10 games',check:s=>s.gamesPlayed>=10},
  {id:'flawless',icon:'💎',name:'Flawless Round',desc:'Get all 5 correct in a round',check:s=>s.flawlessRounds>=1},
  {id:'streak5',icon:'🔥',name:'On Fire',desc:'Get a 5-question streak',check:s=>s.bestStreak>=5},
  {id:'streak10',icon:'🌟',name:'Unstoppable',desc:'Get a 10-question streak',check:s=>s.bestStreak>=10},
  {id:'speed_demon',icon:'⚡',name:'Speed Demon',desc:'Average under 3s per answer (3+ games)',check:s=>s.gamesPlayed>=3&&s.answeredCount>0&&(s.totalAnswerTime/s.answeredCount)<3},
  {id:'comeback',icon:'↩️',name:'Comeback King',desc:'Win after being last in round 1',check:s=>s.comebackWins>=1},
  {id:'ace_topic',icon:'🧠',name:'Topic Expert',desc:'100% on any topic (5+ Qs)',check:s=>{for(const t in s.topicStats)if(s.topicStats[t].total>=5&&s.topicStats[t].correct===s.topicStats[t].total)return true;return false;}},
  {id:'variety',icon:'🌈',name:'Renaissance Mind',desc:'Play 10 different topics',check:s=>Object.keys(s.topicStats).length>=10},
  {id:'high_scorer',icon:'💯',name:'Century',desc:'Score 400+ in a single round',check:s=>s.bestRoundScore>=400},
  {id:'twenty_games',icon:'🎯',name:'Veteran',desc:'Play 20 games',check:s=>s.gamesPlayed>=20},
];
function defaultStats(){return{gamesPlayed:0,wins:0,secondPlace:0,thirdPlace:0,totalCorrect:0,totalAnswered:0,bestStreak:0,bestRoundScore:0,totalAnswerTime:0,answeredCount:0,comebackWins:0,flawlessRounds:0,topicStats:{},achievements:[],matchHistory:[],coins:0,ownedItems:[],selectedAvatar:'default',totalXP:0};}
let playerStats=null,statsLoaded=false;
async function loadStats(){try{const r=await window.storage.get('bb-stats');if(r&&r.value){playerStats=JSON.parse(r.value);const d=defaultStats();for(const k in d)if(!(k in playerStats))playerStats[k]=d[k];}else playerStats=defaultStats();}catch(e){playerStats=defaultStats();}statsLoaded=true;updateCareerBtn();}
async function saveStats(){if(!playerStats)return;try{await window.storage.set('bb-stats',JSON.stringify(playerStats));}catch(e){}}
async function resetStatsData(){playerStats=defaultStats();try{await window.storage.delete('bb-stats');}catch(e){}renderStatsScreen();}
function updateCareerBtn(){if(statsLoaded&&playerStats&&playerStats.gamesPlayed>0)document.getElementById('career-btn').style.display='flex';}
let mt={correct:0,answered:0,totalTime:0,roundScores:[],curStreak:0,bestStreak:0,flawless:false,wasLastR1:false,topicResults:{}};
function resetMT(){mt={correct:0,answered:0,totalTime:0,roundScores:[],curStreak:0,bestStreak:0,flawless:false,wasLastR1:false,topicResults:{}};}
function trackAns(correct,time,tid){mt.answered++;mt.totalTime+=time;if(correct){mt.correct++;mt.curStreak++;if(mt.curStreak>mt.bestStreak)mt.bestStreak=mt.curStreak;}else mt.curStreak=0;if(!mt.topicResults[tid])mt.topicResults[tid]={correct:0,total:0};mt.topicResults[tid].total++;if(correct)mt.topicResults[tid].correct++;}
function trackRound(score,roundCorrect,isR1){mt.roundScores.push(score);if(roundCorrect>=5)mt.flawless=true;if(isR1){const a=getActive(),s=[...a].sort((x,y)=>(y.roundScore||0)-(x.roundScore||0)),mi=s.findIndex(x=>x.name===gs.myName);if(mi>=a.length-1)mt.wasLastR1=true;}}
async function finalizeStats(myPlace,topicIcons){if(!playerStats)await loadStats();const s=playerStats;s.gamesPlayed++;if(myPlace===1)s.wins++;else if(myPlace===2)s.secondPlace++;else if(myPlace===3)s.thirdPlace++;s.totalCorrect+=mt.correct;s.totalAnswered+=mt.answered;s.totalAnswerTime+=mt.totalTime;s.answeredCount+=mt.answered;if(mt.bestStreak>s.bestStreak)s.bestStreak=mt.bestStreak;const br=Math.max(...mt.roundScores,0);if(br>s.bestRoundScore)s.bestRoundScore=br;if(mt.flawless)s.flawlessRounds++;if(myPlace===1&&mt.wasLastR1)s.comebackWins++;for(const t in mt.topicResults){if(!s.topicStats[t])s.topicStats[t]={correct:0,total:0};s.topicStats[t].correct+=mt.topicResults[t].correct;s.topicStats[t].total+=mt.topicResults[t].total;}const earnedCoins=getPlacementCoins(myPlace);s.coins=(s.coins||0)+earnedCoins;const earnedXP=calcGameXP(myPlace,mt.correct,mt.bestStreak);const xpResult=addXP(earnedXP);const nA=[];ACHIEVEMENTS.forEach(a=>{if(!s.achievements.includes(a.id)&&a.check(s)){s.achievements.push(a.id);nA.push(a);}});s.matchHistory.unshift({date:Date.now(),place:myPlace,score:mt.roundScores.reduce((a,b)=>a+b,0),topics:topicIcons||'',correct:mt.correct,total:mt.answered,coinsEarned:earnedCoins,xpEarned:earnedXP});if(s.matchHistory.length>20)s.matchHistory=s.matchHistory.slice(0,20);await saveStats();updateCareerBtn();nA.forEach((a,i)=>setTimeout(()=>showAchToast(a.icon,a.name),1500+i*2500));if(xpResult.leveledup)setTimeout(()=>showLevelUpToast(xpResult.newLevel,xpResult.bonus),800);}
function showAchToast(icon,name){const t=document.getElementById('ach-toast');document.getElementById('ach-toast-icon').textContent=icon;document.getElementById('ach-toast-name').textContent=name;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500);}
function openStats(){if(!playerStats)return;renderStatsScreen();show('s-stats');}
function closeStats(){show('s-lobby');}
function renderStatsScreen(){const s=playerStats;if(!s)return;document.getElementById('stats-avatar').textContent=gs.myName?initials(gs.myName):'??';document.getElementById('stats-pname').textContent=gs.myName||'Player';const titles=[[50,'Grand Master'],[30,'Master'],[20,'Expert'],[10,'Veteran'],[5,'Contender'],[1,'Rookie'],[0,'Newcomer']];document.getElementById('stats-title').textContent=(titles.find(t=>s.gamesPlayed>=t[0])||[0,'Newcomer'])[1];const wr=s.gamesPlayed>0?Math.round(s.wins/s.gamesPlayed*100):0;document.getElementById('wr-pct').textContent=wr+'%';document.getElementById('wr-arc').style.strokeDashoffset=239-(239*wr/100);document.getElementById('wr-wins').textContent=s.wins;document.getElementById('wr-2nd').textContent=s.secondPlace;document.getElementById('wr-3rd').textContent=s.thirdPlace;document.getElementById('st-games').textContent=s.gamesPlayed;document.getElementById('st-accuracy').textContent=(s.totalAnswered>0?Math.round(s.totalCorrect/s.totalAnswered*100):0)+'%';document.getElementById('st-streak').textContent=s.bestStreak;document.getElementById('st-avgtime').textContent=s.answeredCount>0?(s.totalAnswerTime/s.answeredCount).toFixed(1)+'s':'—';document.getElementById('st-best-round').textContent=s.bestRoundScore;const ag=document.getElementById('ach-grid');ag.innerHTML='';ACHIEVEMENTS.forEach(a=>{const u=s.achievements.includes(a.id),d=document.createElement('div');d.className='ach-row '+(u?'unlocked':'locked');d.innerHTML=`<div class="ach-icon">${a.icon}</div><div class="ach-info"><div class="ach-name">${a.name}</div><div class="ach-desc">${a.desc}</div></div>${u?'<div class="ach-check">✓</div>':''}`;ag.appendChild(d);});const tl=document.getElementById('topic-stats-list');tl.innerHTML='';const te=Object.entries(s.topicStats).sort((a,b)=>b[1].total-a[1].total);if(!te.length)tl.innerHTML='<div style="text-align:center;padding:16px;color:#4b5563;font-size:13px;">Play some games first</div>';else te.forEach(([tid,ts])=>{const tp=TOPICS.find(t=>t.id===tid);if(!tp)return;const pct=ts.total>0?Math.round(ts.correct/ts.total*100):0;const d=document.createElement('div');d.className='topic-stat-row';d.innerHTML=`<div class="topic-stat-icon">${tp.icon}</div><div class="topic-stat-name">${tp.name}</div><div class="topic-stat-pct">${pct}%</div>`;tl.appendChild(d);});const ml=document.getElementById('match-list');ml.innerHTML='';if(!s.matchHistory.length)ml.innerHTML='<div class="match-empty">No matches yet</div>';else s.matchHistory.forEach(m=>{const medals=['🥇','🥈','🥉','4th','5th'];const ds=new Date(m.date).toLocaleDateString('en-US',{month:'short',day:'numeric'});const div=document.createElement('div');div.className='match-row';div.innerHTML=`<div class="match-place p${m.place}">${medals[m.place-1]||m.place}</div><div style="flex:1;min-width:0;"><div style="font-size:13px;font-weight:700;color:#d1d5db;">${m.correct}/${m.total} correct</div><div class="match-topics">${m.topics}</div></div><div style="text-align:right;"><div class="match-score">${m.score}</div><div style="font-size:10px;color:#4b5563;margin-top:2px;">${ds}</div></div>`;ml.appendChild(div);});}
function renderPostgame(){const pg=document.getElementById('postgame-stats');pg.innerHTML='';if(!playerStats||!playerStats.gamesPlayed)return;const s=playerStats,wr=s.gamesPlayed>0?Math.round(s.wins/s.gamesPlayed*100):0;const lastMatch=s.matchHistory[0];const coinsEarned=lastMatch?.coinsEarned||0;const xpEarned=lastMatch?.xpEarned||0;const lv=getPlayerLevel();pg.innerHTML=`<div class="postgame-row"><div class="pg-stat"><div class="pg-stat-val">Lv.${lv.level}</div><div class="pg-stat-lbl">${getLevelTitle(lv.level)}</div></div><div class="pg-stat"><div class="pg-stat-val">+${xpEarned}</div><div class="pg-stat-lbl">XP</div></div><div class="pg-stat"><div class="pg-stat-val">+${coinsEarned} 🪙</div><div class="pg-stat-lbl">Coins</div></div><div class="pg-stat"><div class="pg-stat-val">${wr}%</div><div class="pg-stat-lbl">Win Rate</div></div></div>`;}

/* ═══════ AVATAR & COIN & STORE SYSTEM ═══════ */
const AVATARS_FREE=[
  {id:'default',icon:'😀',name:'Smiley'},
  {id:'cool',icon:'😎',name:'Cool'},
  {id:'nerd',icon:'🤓',name:'Nerd'},
  {id:'think',icon:'🤔',name:'Thinker'},
  {id:'fire',icon:'🔥',name:'Fire'},
  {id:'star',icon:'⭐',name:'Star'},
  {id:'bolt',icon:'⚡',name:'Bolt'},
  {id:'ghost',icon:'👻',name:'Ghost'},
];
const AVATARS_PREMIUM=[
  {id:'crown',icon:'👑',name:'Crown',price:100},
  {id:'diamond',icon:'💎',name:'Diamond',price:150},
  {id:'alien',icon:'👽',name:'Alien',price:80},
  {id:'robot',icon:'🤖',name:'Robot',price:80},
  {id:'unicorn',icon:'🦄',name:'Unicorn',price:120},
  {id:'dragon',icon:'🐉',name:'Dragon',price:200},
  {id:'astronaut',icon:'🧑‍🚀',name:'Astronaut',price:150},
  {id:'wizard',icon:'🧙',name:'Wizard',price:120},
  {id:'ninja',icon:'🥷',name:'Ninja',price:100},
  {id:'skull',icon:'💀',name:'Skull',price:80},
  {id:'phoenix',icon:'🦅',name:'Phoenix',price:180},
  {id:'trophy',icon:'🏆',name:'Champion',price:250},
];
const STORE_ITEMS={
  removeAds:{id:'remove_ads',icon:'🚫',name:'Remove Ads',desc:'Enjoy ad-free gameplay forever',price:300},
  topicPacks:[
    {id:'tp_anime',icon:'🎌',name:'Anime & Manga',desc:'25 questions about anime',price:150},
    {id:'tp_food',icon:'🍕',name:'Food & Cooking',desc:'25 questions about cuisine',price:150},
    {id:'tp_nature',icon:'🌿',name:'Nature & Animals',desc:'25 questions about wildlife',price:150},
    {id:'tp_science',icon:'🔬',name:'Science',desc:'25 questions about science',price:150},
  ],
  bundles:[
    {id:'bun_50',icon:'📦',name:'50 Bonus Questions',desc:'Random questions across all topics',price:200},
    {id:'bun_mega',icon:'🎁',name:'Mega Bundle',desc:'100 questions + random premium avatar',price:400},
  ]
};
